// <auto-generated />
using App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210701153628_query2")]
    partial class query2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("App.Grades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Grade")
                        .HasColumnType("REAL");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Science 233",
                            Grade = 0.87,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Comp Sci 1240",
                            Grade = 0.94999999999999996,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Math 303",
                            Grade = 0.65000000000000002,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "History 102",
                            Grade = 0.98999999999999999,
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("App.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 19,
                            FirstName = "Buzz",
                            LastName = "Liteya",
                            Year = "Freshman"
                        },
                        new
                        {
                            Id = 2,
                            Age = 23,
                            FirstName = "Rick",
                            LastName = "Ziggler",
                            Year = "Senior"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            FirstName = "Sheila",
                            LastName = "Jinkees",
                            Year = "Junior"
                        });
                });

            modelBuilder.Entity("App.Grades", b =>
                {
                    b.HasOne("App.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("App.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
